webtalk_init -webtalk_dir D:\\Rohith\\PASSthrough_VITA\\in_2017.4\\16Feb2018\\VITA_passthrough\\project_3\\project_3.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-02-20 15:56:47" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2017.4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211306090_0_0_340" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "2fq0orc9h4v5lg2pt4s1vk6soq" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2017.4_4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "4" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A8-7600 Radeon R7, 10 Compute Cores 4C+6G  " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3094 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "7.434 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1519137050858" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key Processors -value "2" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key VivadoVersion -value "2017.4" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1519137050858"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1519138607062"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1519138607062"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1519138607062"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1519138607062"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1519138607062"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1519138607062"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1519138607062"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1519138607062"
webtalk_transmit -clientid 3300666663 -regid "211306090_0_0_340" -xml D:\\Rohith\\PASSthrough_VITA\\in_2017.4\\16Feb2018\\VITA_passthrough\\project_3\\project_3.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\Rohith\\PASSthrough_VITA\\in_2017.4\\16Feb2018\\VITA_passthrough\\project_3\\project_3.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\Rohith\\PASSthrough_VITA\\in_2017.4\\16Feb2018\\VITA_passthrough\\project_3\\project_3.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
